version: '3.8'

services:
  backend:
    build: ./echopredict_backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    volumes:
      - ./echopredict_backend:/app
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./echopredict_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./echopredict_frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0