[phases.setup]
nixPkgs = ['python39Full']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['cd echopredict_backend && python manage.py collectstatic --noinput']

[start]
cmd = 'cd echopredict_backend && python manage.py migrate && gunicorn echopredict_backend.wsgi:application --bind 0.0.0.0:$PORT'