services:
  - type: web
    name: echopredict-backend
    env: python
    buildCommand: "cd echopredict_backend && pip install -r requirements.txt"
    startCommand: "cd echopredict_backend && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn echopredict_backend.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: echopredict-db
          property: connectionString

databases:
  - name: echopredict-db
    databaseName: echopredict
    user: echopredict